quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./library-soap;AUTO_SERVER=TRUE
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.cxf.path=/soap
quarkus.cxf.endpoint."/LibraryService".implementor=org.library.ws.LibraryWebService